import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'introduction', // Link to docs/introduction.md
      label: 'Introduction',
    },
    {
      type: 'doc',
      id: 'getting-started',
      label: 'Getting Started',
    },
    {
      type: 'category',
      label: 'User Guide',
      items: [
        'frontend', // docs/frontend.md
        'api-reference', // docs/api-reference.md
      ],
    },
    {
      type: 'category',
      label: 'System Details',
      items: [
        'backend', // docs/backend.md
        'deployment', // docs/deployment.md
      ],
    },
    {
      type: 'doc',
      id: 'development', // docs/development.md
      label: 'Development Setup',
    },
  ],
};

export default sidebars;
